In [30]:
import pathlib
import pandas as pd
import random

BASE_DIR = pathlib.Path().resolve().parent
DATASET_DIR = BASE_DIR / "datasets"
EXPORT_DIR = DATASET_DIR / "exports"
EXPORT_DIR.mkdir(exist_ok=True, parents=True)
SPAM_DATASET_PATH = EXPORT_DIR / "spam-dataset.csv"

METADATA_EXPORT_PATH = EXPORT_DIR / 'spam-metadata.pkl'
TOKENIZER_EXPORT_PATH = EXPORT_DIR / 'spam-tokenizer.json'

In [2]:
df = pd.read_csv(SPAM_DATASET_PATH)
df.head()

label                                               text    source
0   ham  Go until jurong point, crazy.. Available only ...  sms-spam
1   ham                      Ok lar... Joking wif u oni...  sms-spam
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...  sms-spam
3   ham  U dun say so early hor... U c already then say...  sms-spam
4   ham  Nah I don't think he goes to usf, he lives aro...  sms-spam

In [3]:
labels = df['label'].tolist()
texts = df['text'].tolist()

In [4]:
labels[120], texts[120]

('spam',
 'PRIVATE! Your 2004 Account Statement for 07742676969 shows 786 unredeemed Bonus Points. To claim call 08719180248 Identifier Code: 45239 Expires')

In [5]:
label_legend = {"ham": 0, "spam": 1}
label_legend_inverted = {f"{v}": k for k,v in label_legend.items()}
label_legend_inverted

{'0': 'ham', '1': 'spam'}

In [6]:
labels_as_int = [label_legend[x] for x in labels]
# label_legend_inverted[str(labels_as_int[120])]

In [7]:
random_idx = random.randint(0, len(labels))

assert texts[random_idx] == df.iloc[random_idx].text

assert labels[random_idx] == df.iloc[random_idx].label

assert label_legend_inverted[str(labels_as_int[random_idx])] == df.iloc[random_idx].label

In [8]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [9]:
MAX_NUM_WORDS = 280

In [10]:
tokenizer = Tokenizer(num_words=MAX_NUM_WORDS)
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)
sequences

[[55, 66, 10, 123, 143, 204, 169, 77, 68, 187],
 [64, 8],
 [59, 10, 25, 4, 2, 211, 95, 2, 2, 110, 104],
 [8, 182, 21, 8, 181, 185, 67, 182],
 [1, 121, 124, 80, 2, 80, 263, 118],
 [94,
  77,
  175,
  136,
  129,
  31,
  6,
  44,
  101,
  38,
  125,
  3,
  41,
  14,
  13,
  92,
  64,
  2,
  93,
  2],
 [208, 7, 9, 32, 38, 2, 40, 12, 113, 12, 38],
 [76, 212, 18, 120, 136, 76, 18, 14, 49, 2, 18, 276],
 [76, 4, 3, 20, 136, 2, 199, 2, 174, 26, 174, 66],
 [166, 18, 141, 37, 114, 8, 111, 2, 2, 5, 40, 14, 59, 26, 5, 141, 249, 59, 16],
 [42, 254, 33, 91, 245, 6, 1, 121, 79, 2, 89, 11, 135, 267, 96],
 [2, 211, 209, 47, 2, 196, 110, 6, 93, 2, 255, 78, 134, 56],
 [257,
  3,
  20,
  216,
  4,
  90,
  159,
  59,
  10,
  88,
  196,
  199,
  110,
  5,
  174,
  2,
  44,
  104,
  181,
  82],
 [267,
  136,
  14,
  5,
  170,
  2,
  195,
  3,
  14,
  11,
  1,
  1,
  107,
  18,
  177,
  14,
  6,
  35,
  7,
  3,
  20,
  136,
  6,
  4,
  34,
  49],
 [1, 20, 4, 16, 40, 35],
 [2, 18, 5, 10, 5, 246, 110, 186, 37, 

In [11]:
word_index = tokenizer.word_index
word_index

{'i': 1,
 'to': 2,
 'you': 3,
 'a': 4,
 'the': 5,
 'and': 6,
 'my': 7,
 'u': 8,
 'is': 9,
 'in': 10,
 'this': 11,
 'me': 12,
 'it': 13,
 'for': 14,
 'of': 15,
 'on': 16,
 'out': 17,
 'your': 18,
 '\ufeff': 19,
 'have': 20,
 'so': 21,
 'that': 22,
 'check': 23,
 'are': 24,
 '2': 25,
 'call': 26,
 'if': 27,
 'but': 28,
 'can': 29,
 'just': 30,
 'now': 31,
 'not': 32,
 'be': 33,
 'at': 34,
 'will': 35,
 'do': 36,
 'or': 37,
 'like': 38,
 'get': 39,
 'with': 40,
 'up': 41,
 "i'm": 42,
 'we': 43,
 'no': 44,
 'love': 45,
 'ur': 46,
 'from': 47,
 'please': 48,
 'all': 49,
 'com': 50,
 'lt': 51,
 'gt': 52,
 'how': 53,
 'when': 54,
 'go': 55,
 '4': 56,
 'video': 57,
 'know': 58,
 'free': 59,
 'am': 60,
 'what': 61,
 'good': 62,
 'was': 63,
 'ok': 64,
 'time': 65,
 'only': 66,
 'then': 67,
 'got': 68,
 'its': 69,
 'song': 70,
 'come': 71,
 '39': 72,
 'youtube': 73,
 'new': 74,
 'br': 75,
 'as': 76,
 'there': 77,
 'day': 78,
 'want': 79,
 'he': 80,
 'one': 81,
 'www': 82,
 'by': 83,
 'amp': 84,
 

In [12]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [13]:
MAX_SEQ_LENGTH = 300

In [14]:
X = pad_sequences(sequences, maxlen=MAX_SEQ_LENGTH)

In [15]:
import numpy as np
from tensorflow.keras.utils import to_categorical

In [16]:
labels_as_int_array = np.asarray(labels_as_int)
labels_as_int_array

array([0, 0, 1, ..., 1, 1, 0])

In [17]:
y = to_categorical(labels_as_int_array)

In [18]:
y

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [19]:
[0, 0, 1]
['ham', 'ham', 'spam']
['ham', 'spam']

[[1, 0], [1,0], [0, 1]]

[[1, 0], [1, 0], [0, 1]]

In [23]:
X, y

(array([[  0,   0,   0, ...,  77,  68, 187],
        [  0,   0,   0, ...,   0,  64,   8],
        [  0,   0,   0, ...,   2, 110, 104],
        ...,
        [  0,   0,   0, ...,  15,   6, 137],
        [  0,   0,   0, ..., 180,  50,  50],
        [  0,   0,   0, ..., 190, 241,  19]], dtype=int32),
 array([[1., 0.],
        [1., 0.],
        [0., 1.],
        ...,
        [0., 1.],
        [0., 1.],
        [1., 0.]], dtype=float32))

In [22]:
!pip install scikit-learn

  Using cached scikit_learn-1.0-cp39-cp39-macosx_10_13_x86_64.whl (8.0 MB)
  Using cached threadpoolctl-3.0.0-py3-none-any.whl (14 kB)
  Using cached joblib-1.0.1-py3-none-any.whl (303 kB)
  Using cached scipy-1.7.1-cp39-cp39-macosx_10_9_x86_64.whl (32.8 MB)


In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_t2 = train_test_split(X, y, test_size=0.5, random_state=42)

X_test, X_valid, y_train, y_test = train_test_split(X_test, y_t2, test_size=0.33, random_state=42)

In [26]:
import pickle

In [31]:
training_data = {
    "X_train": X_train, 
    "X_test": X_test,
    "y_train": y_train,
    "y_test": y_test,
    "max_words": MAX_NUM_WORDS,
    "max_seq_length": MAX_SEQ_LENGTH,
    "label_legend": label_legend,
    "label_legend_inverted": label_legend_inverted, 
}
tokenizer_json = tokenizer.to_json()
TOKENIZER_EXPORT_PATH.write_text(tokenizer_json)

1090335

In [32]:
with open(METADATA_EXPORT_PATH, 'wb') as f:
    pickle.dump(training_data, f)